#!/usr/bin/env bash
set -euo pipefail

for func in 'apt' 'chsh' 'clone' 'deb' 'homebrew' 'link' 'nvm' 'sudoers' ; do
  source "$(dirname "$0")/lib/${func}.sh"
done

# linux config
declare -a linux_prompts=( 'nojhan/liquidprompt' )
declare -a linux_apt=( 'build-essential' 'curl' 'fzf' 'git' 'git-extras' 'gnupg' 'jq' 'ripgrep' 'unzip' 'wget' )
declare -a linux_apt_python=( 'libbz2-dev' 'libffi-dev' 'liblzma-dev' 'libncurses-dev' 'libreadline-dev' 'libsqlite3-dev' )
declare -a linux_deb=( 'cli/cli' 'lsd-rs/lsd' 'sharkdp/bat' 'sharkdp/fd' 'dandavison/delta' 'ajeetdsouza/zoxide' )

# linux
if [[ $(uname) == 'Linux' ]] ; then
  echo 'Symlinking dotfiles...'
  dotfiles_link shared linux

  echo 'Installing apt packages...'
  dotfiles_apt "${linux_apt[@]}" "${linux_apt_python[@]}"

  echo 'Installing deb packages...'
  dotfiles_deb "${linux_deb[@]}"

  # install prompts with homebrew on mac
  echo 'Installing prompts...'
  dotfiles_clone "${linux_prompts[@]}"
fi

# mac
if [[ $(uname) == 'Darwin' ]] ; then
  echo 'Symlinking dotfiles...'
  dotfiles_link shared mac

  # requires relogin to take effect
  echo 'Enabling passwordless sudo...'
  dotfiles_sudoers

  echo 'Installing Homebrew...'
  dotfiles_homebrew

  echo 'Installing Homebrew packages...'
  eval "$(brew shellenv)"
  brew bundle --global --no-lock

  # requires fish (in Brewfile)
  echo 'Installing Fish plugins...'
  fish -c 'fisher update'

  # requires relogin
  echo 'Changing default shell to Fish...'
  dotfiles_chsh '/usr/local/bin/fish'

  # command + shift + .
  echo 'Showing hidden files in Finder...'
  defaults write com.apple.finder AppleShowAllFiles true
  killall Finder

  echo 'Installing nvm and Node LTS...'
  dotfiles_nvm 'lts/*'
fi

echo 'Done! 🎉'
